CREATE TABLE USUARIO (

ID INT PRIMARY KEY,
USER_NAME VARCHAR(255),
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(255),
ROLE VARCHAR(255),
SSN VARCHAR(255)

);

INSERT INTO USUARIO VALUES (101, 'VALE@FICO.COM', 'VALE','CALZADA','ADMIN','SSN01','VALECALZADA');