pipeline {
    agent any
    tools {
        maven 'maven-jenkins-installation-3.9.8'//local
    }

    stages {

        stage('Git Checkout') {
            steps {
                   checkout scmGit(
                        branches: [[name: '*/master']], 
                        extensions: [], 
                        userRemoteConfigs: [[url: "https://github.com/ValeriaCalzada/demoRest.git"]]
                        )
                    echo 'Git Checkout Completed'
            }
        }

        stage('Call External Endpoint') {
            steps {
                script {
                    // Use environment variables if they are set
                    def endpointUrl = "https://pokeapi.co/api/v2/pokemon/${params.POKEMON_NAME}"
                    
                    // Call the external endpoint
                    def response = httpRequest url: endpointUrl, validResponseCodes: '200:299'

                    // Process the response
                    def jsonResponse = readJSON text: response.content
                    echo "Response from API: ${jsonResponse}"
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQServer') {
                    sh '''
                        mvn clean verify sonar:sonar -Dsonar.projectKey=DemoProjectSonarGithub -Dsonar.projectName='DemoProjectSonarGithub' -Dsonar.host.url=http://sonar:9000 -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
                    '''
                    echo 'SonarQube Analysis Completed'
                }
            }
        }
    }
}